In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [24]:
from pathlib import Path
import pandas as pd
import os


from methylseg import MethylSegPathway, MethylDataPrep, HMMType

In [17]:
ip = get_ipython()
if "__vsc_ipynb_file__" in ip.user_ns:
    NOTEBOOK_PATH = Path(ip.user_ns["__vsc_ipynb_file__"]).resolve()
else:
    NOTEBOOK_PATH = Path("analysis/shared_utils/methylseg/examples/run_full_pipeline.ipynb").resolve()

EXAMPLES_DIR = NOTEBOOK_PATH.parent
METHYL_SEG_PATH_PARENT = EXAMPLES_DIR.parent
DATA_DIR = METHYL_SEG_PATH_PARENT / Path("data")
REFERENCE_DIR = DATA_DIR / Path("reference_files")

In [18]:
wgbs_test_sample_info, wgbs_test_sample_info_removed = MethylDataPrep(
    meth_file=REFERENCE_DIR / "WGBS_colon-primary-tumor_1_wgbs.tsv.gz",
    sample_id="WGBS_colon-primary-tumor_1",
    resolution="wgbs",
    min_coverage=10,
    remove_low_coverage_like_cpgs=True,
).prepare()

In [ ]:
meth_seg_pathway = MethylSegPathway(
    train_sample_info=wgbs_test_sample_info,
    hmm_type=HMMType.STICKY,
    hmm_params={
        "stay_prob": 0.99995,
        "emission_mismatch_prob": 0.45,
        "fit_transitions": False,
    },
    out_dir=EXAMPLES_DIR / "out" / "full_pipeline_output_wgbs"
)

In [20]:
region_paths = meth_seg_pathway.run_pathway()

Fitting pathway...
Generating regions ...

In [21]:
pd.read_csv(region_paths[3], sep="\t").head()

   chr1    68238   104048  PMD
0  chr1   268411   509511  PMD
1  chr1  1110605  1153357  PMD
2  chr1  2432555  2632688  PMD
3  chr1  2773024  3251489  PMD
4  chr1  3384523  3719496  PMD

In [ ]:
hm450k_test_sample_info, hm450k_test_sample_info_removed = MethylDataPrep(
    meth_file=REFERENCE_DIR / "WGBS_colon-primary-tumor_1_450k.beta.gz",
    sample_id="colon-primary-tumor_1_450k",
    resolution="450k",
    remove_low_coverage_like_cpgs=True,
).prepare()

In [26]:
meth_seg_pathway = MethylSegPathway(
    train_sample_info=hm450k_test_sample_info,
    hmm_type=HMMType.CT,
    hmm_params={},
    out_dir=EXAMPLES_DIR / "out" / "full_pipeline_output_hm450"
)

In [27]:
region_paths = meth_seg_pathway.run_pathway()

Fitting pathway...
Generating regions ...

In [28]:
pd.read_csv(region_paths[3], sep="\t").head()

   chr1   995946  1001669  PMD
0  chr1  1127805  1158701  PMD
1  chr1  2684250  2888586  PMD
2  chr1  3001541  3090192  PMD
3  chr1  3553112  3560739  PMD
4  chr1  4507143  4668783  PMD